# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72f238e97716e1fc0bf58f2b6b4a4c08b1ee7346488040c482a00721b093c58935970c3478d2b961d4da30e6fbf0bb8dcaecbb9436c92a39a7c0fd339d6453aa
  DEVELOPMENT_DATABASE_URL: postgres://zdzbzwdatnyenx:b05eebb03e296fec0684e8f35df7b30c9c6df520657e35dbbb8fa0c305e95a57@ec2-54-246-115-40.eu-west-1.compute.amazonaws.com:5432/d2se8c9304dass
  SENDGRID_API_KEY: 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

test:
  secret_key_base: 0b3517aa2d898b5a23462ce7a34cec67cf628077e9ff7997a686be57eb24589a72d703e50c4339d28211cf3cae361eb7d4979df4305f7bc2e4da4f59773203c7
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  PRODUCTION_DATABASE_URL: postgres://btipiexhzrgsuu:b1968175f9f34dac8dbed20a9579e0fb629a4e55017c4aac62dc77e00fc06fe4@ec2-52-30-161-203.eu-west-1.compute.amazonaws.com:5432/d74n6eodbtfgt4