test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  
google:
  service: GCS
  project: "My First Project"
  credentials: <%= Rails.root.join("config/keyfile.json") %>
  bucket: "lizard-active-storage"